#!/bin/bash

firebaseURL=""

function playWithShuffle {
	killall mpv
	params=$([ "$1" == true ] && echo "--shuffle" || echo "")
	echo $params
	mpv --no-video $params --idle --input-ipc-server=/tmp/mpvsocket $2
}

function editPlaylist {
	curl $firebaseURL | jq > /tmp/p.json
	vim /tmp/p.json
	curl -s -X PUT -H "Content-Type: application/json" -d @/tmp/p.json $firebaseURL > /dev/null
}

if [ "$1" == "-m" ]; then
	url=$(curl $firebaseURL | jq -r '. | .[] | .name + " - " + .url' | rofi -font "Source Code Pro 10" -dmenu -p "Select Track" -i | egrep -o 'https?://[^ ]+')
	if [ ! -z "${url}" ]; then
		if [[ $url == *"youtube"* || $url == *"soundcloud"* ]]; then
			choice=$(printf "No\nYes" | rofi -dmenu -font "Source Code Pro 10" -p "Shuffle?" -i)
			if [ "$choice" == "Yes" ]; then playWithShuffle true $url; else playWithShuffle false $url; fi
		else
			playWithShuffle false $url
		fi
	fi
fi

if [ "$1" == "-e" ]; then
	editPlaylist
fi

if [ "$1" == "" ]; then
	echo "Pinenut v1.0 - A tiny rofi based music selector for mpv"
	echo "Usage : pinenut [options]"
	echo ""
	echo "Options :"
	echo " -m		play selected track from playlist"
	echo " -e		edit the playlist and post"
	echo ""
fi
